// SPDX-License-Identifier: GPL-3.0-only
package com.auralis.core.domain

/**
 * Stable fixed taxonomy shared by Android Recommendation Index classification and Categories.
 *
 * The IDs/display names are generated from Apple's RecommendationIndexTaxonomy. Runtime code
 * never accepts a free-form textual tag; only these immutable IDs can be persisted.
 */
data class RecommendationTagDefinition(
    val dimension: String,
    val id: String,
    val displayName: String,
)

object RecommendationIndexTaxonomy {
    private fun t(dimension: String, id: String, displayName: String) =
        RecommendationTagDefinition(dimension = dimension, id = id, displayName = displayName)

    val definitions: List<RecommendationTagDefinition> by lazy {
        listOf(
        t("mood", "mood.calm", "平静"),
        t("mood", "mood.peaceful", "宁静"),
        t("mood", "mood.serene", "平和"),
        t("mood", "mood.relaxed", "放松"),
        t("mood", "mood.soothing", "舒缓"),
        t("mood", "mood.healing", "治愈"),
        t("mood", "mood.comforting", "安慰"),
        t("mood", "mood.warm", "温暖"),
        t("mood", "mood.soft", "柔和"),
        t("mood", "mood.light", "轻盈"),
        t("mood", "mood.fresh", "清新"),
        t("mood", "mood.cozy", "惬意"),
        t("mood", "mood.languid", "慵懒"),
        t("mood", "mood.leisurely", "闲适"),
        t("mood", "mood.restrained", "克制"),
        t("mood", "mood.quiet", "沉静"),
        t("mood", "mood.bright", "明亮"),
        t("mood", "mood.sunny", "阳光"),
        t("mood", "mood.happy", "快乐"),
        t("mood", "mood.joyful", "欢乐"),
        t("mood", "mood.delight", "喜悦"),
        t("mood", "mood.excited", "兴奋"),
        t("mood", "mood.ecstatic", "狂喜"),
        t("mood", "mood.uplifting", "振奋"),
        t("mood", "mood.inspiring", "鼓舞"),
        t("mood", "mood.hopeful", "希望"),
        t("mood", "mood.optimistic", "乐观"),
        t("mood", "mood.confident", "自信"),
        t("mood", "mood.unfettered", "洒脱"),
        t("mood", "mood.free", "自由"),
        t("mood", "mood.brisk", "爽快"),
        t("mood", "mood.lively", "活泼"),
        t("mood", "mood.playful", "俏皮"),
        t("mood", "mood.cute", "可爱"),
        t("mood", "mood.sweet", "甜蜜"),
        t("mood", "mood.romantic", "浪漫"),
        t("mood", "mood.affectionate", "深情"),
        t("mood", "mood.tender", "温柔"),
        t("mood", "mood.intimate", "亲密"),
        t("mood", "mood.sensual", "感性"),
        t("mood", "mood.sexy", "性感"),
        t("mood", "mood.seductive", "诱惑"),
        t("mood", "mood.passionate_love", "热恋"),
        t("mood", "mood.cherishing", "眷恋"),
        t("mood", "mood.yearning", "思念"),
        t("mood", "mood.nostalgic", "怀旧"),
        t("mood", "mood.melancholic", "惆怅"),
        t("mood", "mood.bittersweet", "苦涩"),
        t("mood", "mood.sad", "悲伤"),
        t("mood", "mood.gloomy", "忧郁"),
        t("mood", "mood.lonely", "孤独"),
        t("mood", "mood.lost", "失落"),
        t("mood", "mood.heartbroken", "心碎"),
        t("mood", "mood.mournful", "哀伤"),
        t("mood", "mood.grieving", "哀悼"),
        t("mood", "mood.bleak", "悲凉"),
        t("mood", "mood.desolate", "苍凉"),
        t("mood", "mood.helpless", "无奈"),
        t("mood", "mood.tired", "疲惫"),
        t("mood", "mood.dark", "黑暗"),
        t("mood", "mood.oppressive", "压抑"),
        t("mood", "mood.despairing", "绝望"),
        t("mood", "mood.cold", "冷冽"),
        t("mood", "mood.detached", "疏离"),
        t("mood", "mood.hollow", "空洞"),
        t("mood", "mood.heavy", "沉重"),
        t("mood", "mood.sinister", "肃杀"),
        t("mood", "mood.introspective", "内省"),
        t("mood", "mood.contemplative", "沉思"),
        t("mood", "mood.reflective", "反思"),
        t("mood", "mood.reconciled", "释然"),
        t("mood", "mood.philosophical", "哲思"),
        t("mood", "mood.profound", "深邃"),
        t("mood", "mood.earnest", "认真"),
        t("mood", "mood.sensitive", "敏感"),
        t("mood", "mood.fragile", "脆弱"),
        t("mood", "mood.solemn", "庄严"),
        t("mood", "mood.sacred", "神圣"),
        t("mood", "mood.sublime", "崇高"),
        t("mood", "mood.epic", "史诗"),
        t("mood", "mood.grand", "宏大"),
        t("mood", "mood.heroic", "英雄"),
        t("mood", "mood.triumphant", "胜利"),
        t("mood", "mood.steadfast", "坚定"),
        t("mood", "mood.majestic", "壮阔"),
        t("mood", "mood.tragic_heroic", "悲壮"),
        t("mood", "mood.awe", "敬畏"),
        t("mood", "mood.fervent", "热烈"),
        t("mood", "mood.fiery", "激情"),
        t("mood", "mood.intense", "强烈"),
        t("mood", "mood.rousing", "激昂"),
        t("mood", "mood.burning", "燃"),
        t("mood", "mood.urgent", "急迫"),
        t("mood", "mood.restless", "躁动"),
        t("mood", "mood.wild", "狂野"),
        t("mood", "mood.explosive", "爆发"),
        t("mood", "mood.cathartic", "宣泄"),
        t("mood", "mood.tense", "紧张"),
        t("mood", "mood.anxious", "焦虑"),
        t("mood", "mood.uneasy", "不安"),
        t("mood", "mood.suspenseful", "悬疑"),
        t("mood", "mood.dangerous", "危险"),
        t("mood", "mood.pressured", "压迫"),
        t("mood", "mood.fearful", "恐惧"),
        t("mood", "mood.horror", "惊悚"),
        t("mood", "mood.eerie", "诡异"),
        t("mood", "mood.haunting", "阴森"),
        t("mood", "mood.threatening", "威胁"),
        t("mood", "mood.mysterious", "神秘"),
        t("mood", "mood.ethereal", "空灵"),
        t("mood", "mood.dreamy", "梦幻"),
        t("mood", "mood.hazy", "迷离"),
        t("mood", "mood.hypnotic", "催眠"),
        t("mood", "mood.psychedelic", "迷幻"),
        t("mood", "mood.surreal", "超现实"),
        t("mood", "mood.fantastical", "奇幻"),
        t("mood", "mood.magical", "魔幻"),
        t("mood", "mood.futuristic", "未来感"),
        t("mood", "mood.cosmic", "宇宙感"),
        t("mood", "mood.angry", "愤怒"),
        t("mood", "mood.aggressive", "攻击性"),
        t("mood", "mood.radical", "激进"),
        t("mood", "mood.rebellious", "叛逆"),
        t("mood", "mood.provocative", "挑衅"),
        t("mood", "mood.hostile", "敌意"),
        t("mood", "mood.gritty", "粗粝"),
        t("mood", "mood.ferocious", "凶猛"),
        t("mood", "mood.violent", "暴烈"),
        t("mood", "mood.chaotic", "混乱"),
        t("mood", "mood.dramatic", "戏剧化"),
        t("mood", "mood.glamorous", "华丽"),
        t("mood", "mood.exaggerated", "夸张"),
        t("mood", "mood.festive", "庆典感"),
        t("mood", "mood.ceremonial", "仪式感"),
        t("mood", "mood.witty", "戏谑"),
        t("mood", "mood.humorous", "幽默"),
        t("mood", "mood.absurd", "荒诞"),
        t("scene", "scene.early_morning", "清晨"),
        t("scene", "scene.morning", "早晨"),
        t("scene", "scene.late_morning", "上午"),
        t("scene", "scene.noon", "午间"),
        t("scene", "scene.afternoon", "午后"),
        t("scene", "scene.dusk", "黄昏"),
        t("scene", "scene.evening", "傍晚"),
        t("scene", "scene.night", "夜晚"),
        t("scene", "scene.late_night", "深夜"),
        t("scene", "scene.pre_dawn", "凌晨"),
        t("scene", "scene.bedtime", "睡前"),
        t("scene", "scene.waking_up", "起床"),
        t("scene", "scene.commute", "通勤"),
        t("scene", "scene.work", "工作"),
        t("scene", "scene.office", "办公"),
        t("scene", "scene.study", "学习"),
        t("scene", "scene.focus", "专注"),
        t("scene", "scene.reading", "阅读"),
        t("scene", "scene.writing", "写作"),
        t("scene", "scene.coding", "编程"),
        t("scene", "scene.exam", "做题"),
        t("scene", "scene.creative_work", "创作"),
        t("scene", "scene.drawing", "画画"),
        t("scene", "scene.background", "背景音乐"),
        t("scene", "scene.work_break", "工作休息"),
        t("scene", "scene.study_sprint", "学习冲刺"),
        t("scene", "scene.home", "居家"),
        t("scene", "scene.cooking", "做饭"),
        t("scene", "scene.dining", "吃饭"),
        t("scene", "scene.breakfast", "早餐"),
        t("scene", "scene.lunch", "午餐"),
        t("scene", "scene.dinner", "晚餐"),
        t("scene", "scene.cleaning", "清洁"),
        t("scene", "scene.housework", "家务"),
        t("scene", "scene.organizing", "整理房间"),
        t("scene", "scene.shower", "洗澡"),
        t("scene", "scene.bath", "泡澡"),
        t("scene", "scene.daydreaming", "发呆"),
        t("scene", "scene.nap", "午休"),
        t("scene", "scene.siesta", "小憩"),
        t("scene", "scene.meditation", "冥想"),
        t("scene", "scene.yoga", "瑜伽"),
        t("scene", "scene.stretching", "拉伸"),
        t("scene", "scene.sleeping", "睡眠"),
        t("scene", "scene.getting_ready", "起床准备"),
        t("scene", "scene.walking", "散步"),
        t("scene", "scene.city_walk", "城市漫步"),
        t("scene", "scene.park", "公园"),
        t("scene", "scene.hiking", "徒步"),
        t("scene", "scene.mountaineering", "登山"),
        t("scene", "scene.camping", "露营"),
        t("scene", "scene.seaside", "海边"),
        t("scene", "scene.wilderness", "山野"),
        t("scene", "scene.outdoor", "户外"),
        t("scene", "scene.sunset_viewing", "看日落"),
        t("scene", "scene.stargazing", "看星空"),
        t("scene", "scene.running", "跑步"),
        t("scene", "scene.night_running", "夜跑"),
        t("scene", "scene.fitness", "健身"),
        t("scene", "scene.strength_training", "力量训练"),
        t("scene", "scene.cardio", "有氧运动"),
        t("scene", "scene.cycling", "骑行"),
        t("scene", "scene.warmup", "热身"),
        t("scene", "scene.sprint", "运动冲刺"),
        t("scene", "scene.recovery", "运动恢复"),
        t("scene", "scene.driving", "驾车"),
        t("scene", "scene.night_driving", "夜间驾车"),
        t("scene", "scene.long_drive", "长途驾车"),
        t("scene", "scene.road_trip", "公路旅行"),
        t("scene", "scene.subway", "地铁"),
        t("scene", "scene.bus", "公交"),
        t("scene", "scene.train", "火车"),
        t("scene", "scene.high_speed_rail", "高铁"),
        t("scene", "scene.flight", "飞行"),
        t("scene", "scene.waiting", "候机"),
        t("scene", "scene.travel", "旅行"),
        t("scene", "scene.friends_gathering", "朋友小聚"),
        t("scene", "scene.family_gathering", "家庭聚会"),
        t("scene", "scene.party", "聚会"),
        t("scene", "scene.club", "派对"),
        t("scene", "scene.nightclub", "夜店"),
        t("scene", "scene.bar", "酒吧"),
        t("scene", "scene.cafe", "咖啡馆"),
        t("scene", "scene.afternoon_tea", "下午茶"),
        t("scene", "scene.date", "约会"),
        t("scene", "scene.romantic_dinner", "浪漫晚餐"),
        t("scene", "scene.wedding", "婚礼"),
        t("scene", "scene.birthday", "生日"),
        t("scene", "scene.celebration", "庆祝"),
        t("scene", "scene.holiday", "节日"),
        t("scene", "scene.rainy", "雨天"),
        t("scene", "scene.storm", "暴雨"),
        t("scene", "scene.overcast", "阴天"),
        t("scene", "scene.cloudy", "多云"),
        t("scene", "scene.sunny", "晴天"),
        t("scene", "scene.snowy", "雪天"),
        t("scene", "scene.foggy", "雾天"),
        t("scene", "scene.thunder", "雷雨"),
        t("scene", "scene.hot_weather", "炎热天气"),
        t("scene", "scene.cold_weather", "寒冷天气"),
        t("scene", "scene.spring", "春日"),
        t("scene", "scene.summer", "夏日"),
        t("scene", "scene.autumn", "秋日"),
        t("scene", "scene.winter", "冬日"),
        t("scene", "scene.bedroom", "卧室"),
        t("scene", "scene.living_room", "客厅"),
        t("scene", "scene.library", "图书馆"),
        t("scene", "scene.city_night", "城市夜景"),
        t("theme", "theme.love", "爱情"),
        t("theme", "theme.new_love", "新恋情"),
        t("theme", "theme.infatuation", "热恋"),
        t("theme", "theme.confession", "告白"),
        t("theme", "theme.dating", "约会"),
        t("theme", "theme.intimacy", "亲密关系"),
        t("theme", "theme.ambiguity", "暧昧"),
        t("theme", "theme.unrequited_love", "单恋"),
        t("theme", "theme.breakup", "失恋"),
        t("theme", "theme.separation", "分手"),
        t("theme", "theme.heartache", "心碎"),
        t("theme", "theme.longing", "思念"),
        t("theme", "theme.reunion", "重逢"),
        t("theme", "theme.farewell", "告别"),
        t("theme", "theme.friendship", "友情"),
        t("theme", "theme.family", "家庭"),
        t("theme", "theme.kinship", "亲情"),
        t("theme", "theme.youth", "青春"),
        t("theme", "theme.growth", "成长"),
        t("theme", "theme.adulthood", "成年"),
        t("theme", "theme.memories", "回忆"),
        t("theme", "theme.past", "怀念过去"),
        t("theme", "theme.hometown", "故乡"),
        t("theme", "theme.nostalgia", "乡愁"),
        t("theme", "theme.solitude_companion", "孤独陪伴"),
        t("theme", "theme.self_healing", "自我疗愈"),
        t("theme", "theme.self_acceptance", "自我接纳"),
        t("theme", "theme.comfort", "安慰"),
        t("theme", "theme.emptiness", "放空"),
        t("theme", "theme.reflection", "反思"),
        t("theme", "theme.self_examination", "自省"),
        t("theme", "theme.new_beginning", "重新开始"),
        t("theme", "theme.hope", "希望"),
        t("theme", "theme.freedom", "自由"),
        t("theme", "theme.dreams", "梦想"),
        t("theme", "theme.adventure", "冒险"),
        t("theme", "theme.travel_longing", "旅行向往"),
        t("theme", "theme.city_life", "城市生活"),
        t("theme", "theme.nature", "自然"),
        t("theme", "theme.future", "未来"),
        t("theme", "theme.technology", "科技"),
        t("theme", "theme.cosmos", "宇宙"),
        t("theme", "theme.dreamland", "梦境"),
        t("theme", "theme.fantasy", "幻想"),
        t("theme", "theme.religion", "宗教"),
        t("theme", "theme.faith", "信仰"),
        t("theme", "theme.spirituality", "灵性"),
        t("theme", "theme.celebration", "庆祝"),
        t("theme", "theme.victory", "胜利"),
        t("theme", "theme.graduation", "毕业"),
        t("theme", "theme.wedding", "婚礼"),
        t("theme", "theme.festival", "节日"),
        t("theme", "theme.sports_motivation", "运动动力"),
        t("theme", "theme.work_motivation", "工作动力"),
        t("theme", "theme.study_motivation", "学习动力"),
        t("theme", "theme.alertness", "清醒提神"),
        t("theme", "theme.sleep_aid", "助眠"),
        t("theme", "theme.emotional_release", "情绪释放"),
        t("theme", "theme.anger_release", "愤怒释放"),
        t("theme", "theme.sadness_companion", "悲伤陪伴"),
        t("theme", "theme.background_companion", "背景陪伴"),
        t("theme", "theme.party_excitement", "派对狂欢"),
        t("theme", "theme.romantic_mood", "浪漫氛围"),
        t("theme", "theme.sensual_mood", "性感氛围"),
        t("theme", "theme.cinematic", "电影感"),
        t("theme", "theme.epic_narrative", "史诗叙事"),
        t("theme", "theme.heroic_narrative", "英雄叙事"),
        t("theme", "theme.social_observation", "社会观察"),
        t("theme", "theme.rebellion", "反抗"),
        t("theme", "theme.resistance", "抗争"),
        t("theme", "theme.peace", "和平"),
        t("theme", "theme.war", "战争"),
        t("theme", "theme.death", "死亡"),
        t("theme", "theme.life", "生命"),
        t("theme", "theme.time", "时间"),
        t("theme", "theme.memory", "记忆"),
        t("genre", "genre.pop", "流行"),
        t("genre", "genre.rock", "摇滚"),
        t("genre", "genre.electronic", "电子音乐"),
        t("genre", "genre.hip_hop", "嘻哈"),
        t("genre", "genre.r_and_b_soul", "R&B / Soul"),
        t("genre", "genre.jazz", "爵士"),
        t("genre", "genre.classical", "古典音乐"),
        t("genre", "genre.folk", "民谣 / Singer-Songwriter"),
        t("genre", "genre.metal", "金属"),
        t("genre", "genre.punk", "朋克"),
        t("genre", "genre.blues", "蓝调"),
        t("genre", "genre.country", "乡村"),
        t("genre", "genre.funk", "放克"),
        t("genre", "genre.disco", "迪斯科 / 舞曲"),
        t("genre", "genre.reggae", "雷鬼 / Jamaican"),
        t("genre", "genre.latin", "拉丁"),
        t("genre", "genre.world", "世界音乐"),
        t("genre", "genre.traditional", "传统 / 民族音乐"),
        t("genre", "genre.ambient", "Ambient / New Age"),
        t("genre", "genre.soundtrack", "Soundtrack / 配乐"),
        t("genre", "genre.experimental", "实验 / 先锋"),
        t("genre", "genre.gospel", "宗教 / Gospel"),
        t("genre", "genre.children", "儿童音乐"),
        t("genre", "genre.comedy", "喜剧 / Novelty"),
        t("genre", "genre.musical", "音乐剧"),
        t("genre", "genre.chinese_opera", "戏曲 / 曲艺"),
        t("style", "style.dance_pop", "Dance Pop"),
        t("style", "style.synth_pop", "Synth-pop"),
        t("style", "style.electropop", "Electropop"),
        t("style", "style.indie_pop", "Indie Pop"),
        t("style", "style.art_pop", "Art Pop"),
        t("style", "style.dream_pop", "Dream Pop"),
        t("style", "style.chamber_pop", "Chamber Pop"),
        t("style", "style.baroque_pop", "Baroque Pop"),
        t("style", "style.power_pop", "Power Pop"),
        t("style", "style.pop_rock", "Pop Rock"),
        t("style", "style.teen_pop", "Teen Pop"),
        t("style", "style.adult_contemporary", "Adult Contemporary"),
        t("style", "style.sophisti_pop", "Sophisti-pop"),
        t("style", "style.city_pop", "City Pop"),
        t("style", "style.j_pop", "J-Pop"),
        t("style", "style.k_pop", "K-Pop"),
        t("style", "style.c_pop", "C-Pop"),
        t("style", "style.mandopop", "Mandopop"),
        t("style", "style.cantopop", "Cantopop"),
        t("style", "style.sunshine_pop", "Sunshine Pop"),
        t("style", "style.psychedelic_pop", "Psychedelic Pop"),
        t("style", "style.hyperpop", "Hyperpop"),
        t("style", "style.bedroom_pop", "Bedroom Pop"),
        t("style", "style.bubblegum_pop", "Bubblegum Pop"),
        t("style", "style.folk_pop", "Folk Pop"),
        t("style", "style.pop_rap", "Pop Rap"),
        t("style", "style.alternative_pop", "Alternative Pop"),
        t("style", "style.indietronica", "Indietronica"),
        t("style", "style.classic_rock", "Classic Rock"),
        t("style", "style.alternative_rock", "Alternative Rock"),
        t("style", "style.indie_rock", "Indie Rock"),
        t("style", "style.art_rock", "Art Rock"),
        t("style", "style.progressive_rock", "Progressive Rock"),
        t("style", "style.psychedelic_rock", "Psychedelic Rock"),
        t("style", "style.hard_rock", "Hard Rock"),
        t("style", "style.soft_rock", "Soft Rock"),
        t("style", "style.arena_rock", "Arena Rock"),
        t("style", "style.garage_rock", "Garage Rock"),
        t("style", "style.glam_rock", "Glam Rock"),
        t("style", "style.blues_rock", "Blues Rock"),
        t("style", "style.folk_rock", "Folk Rock"),
        t("style", "style.country_rock", "Country Rock"),
        t("style", "style.southern_rock", "Southern Rock"),
        t("style", "style.surf_rock", "Surf Rock"),
        t("style", "style.post_rock", "Post-Rock"),
        t("style", "style.math_rock", "Math Rock"),
        t("style", "style.noise_rock", "Noise Rock"),
        t("style", "style.shoegaze", "Shoegaze"),
        t("style", "style.grunge", "Grunge"),
        t("style", "style.britpop", "Britpop"),
        t("style", "style.gothic_rock", "Gothic Rock"),
        t("style", "style.stoner_rock", "Stoner Rock"),
        t("style", "style.krautrock", "Krautrock"),
        t("style", "style.rockabilly", "Rockabilly"),
        t("style", "style.experimental_rock", "Experimental Rock"),
        t("style", "style.space_rock", "Space Rock"),
        t("style", "style.post_grunge", "Post-Grunge"),
        t("style", "style.punk_rock", "Punk Rock"),
        t("style", "style.pop_punk", "Pop Punk"),
        t("style", "style.post_punk", "Post-Punk"),
        t("style", "style.hardcore_punk", "Hardcore Punk"),
        t("style", "style.post_hardcore", "Post-Hardcore"),
        t("style", "style.emo", "Emo"),
        t("style", "style.screamo", "Screamo"),
        t("style", "style.skate_punk", "Skate Punk"),
        t("style", "style.garage_punk", "Garage Punk"),
        t("style", "style.crust_punk", "Crust Punk"),
        t("style", "style.anarcho_punk", "Anarcho-Punk"),
        t("style", "style.oi", "Oi!"),
        t("style", "style.new_wave", "New Wave"),
        t("style", "style.no_wave", "No Wave"),
        t("style", "style.heavy_metal", "Heavy Metal"),
        t("style", "style.thrash_metal", "Thrash Metal"),
        t("style", "style.death_metal", "Death Metal"),
        t("style", "style.melodic_death_metal", "Melodic Death Metal"),
        t("style", "style.black_metal", "Black Metal"),
        t("style", "style.doom_metal", "Doom Metal"),
        t("style", "style.sludge_metal", "Sludge Metal"),
        t("style", "style.stoner_metal", "Stoner Metal"),
        t("style", "style.power_metal", "Power Metal"),
        t("style", "style.symphonic_metal", "Symphonic Metal"),
        t("style", "style.progressive_metal", "Progressive Metal"),
        t("style", "style.folk_metal", "Folk Metal"),
        t("style", "style.gothic_metal", "Gothic Metal"),
        t("style", "style.nu_metal", "Nu Metal"),
        t("style", "style.metalcore", "Metalcore"),
        t("style", "style.deathcore", "Deathcore"),
        t("style", "style.industrial_metal", "Industrial Metal"),
        t("style", "style.alternative_metal", "Alternative Metal"),
        t("style", "style.post_metal", "Post-Metal"),
        t("style", "style.speed_metal", "Speed Metal"),
        t("style", "style.glam_metal", "Glam Metal"),
        t("style", "style.atmospheric_black_metal", "Atmospheric Black Metal"),
        t("style", "style.technical_death_metal", "Technical Death Metal"),
        t("style", "style.house", "House"),
        t("style", "style.deep_house", "Deep House"),
        t("style", "style.tech_house", "Tech House"),
        t("style", "style.progressive_house", "Progressive House"),
        t("style", "style.electro_house", "Electro House"),
        t("style", "style.future_house", "Future House"),
        t("style", "style.tropical_house", "Tropical House"),
        t("style", "style.acid_house", "Acid House"),
        t("style", "style.techno", "Techno"),
        t("style", "style.minimal_techno", "Minimal Techno"),
        t("style", "style.detroit_techno", "Detroit Techno"),
        t("style", "style.industrial_techno", "Industrial Techno"),
        t("style", "style.trance", "Trance"),
        t("style", "style.progressive_trance", "Progressive Trance"),
        t("style", "style.psytrance", "Psytrance"),
        t("style", "style.uplifting_trance", "Uplifting Trance"),
        t("style", "style.drum_and_bass", "Drum & Bass"),
        t("style", "style.liquid_dnb", "Liquid Drum & Bass"),
        t("style", "style.jungle", "Jungle"),
        t("style", "style.breakbeat", "Breakbeat"),
        t("style", "style.uk_garage", "UK Garage"),
        t("style", "style.two_step", "2-Step"),
        t("style", "style.dubstep", "Dubstep"),
        t("style", "style.future_bass", "Future Bass"),
        t("style", "style.edm_trap", "EDM Trap"),
        t("style", "style.hardstyle", "Hardstyle"),
        t("style", "style.hardcore", "Hardcore"),
        t("style", "style.gabber", "Gabber"),
        t("style", "style.ambient", "Ambient"),
        t("style", "style.dark_ambient", "Dark Ambient"),
        t("style", "style.downtempo", "Downtempo"),
        t("style", "style.chillout", "Chillout"),
        t("style", "style.trip_hop", "Trip-Hop"),
        t("style", "style.idm", "IDM"),
        t("style", "style.glitch", "Glitch"),
        t("style", "style.vaporwave", "Vaporwave"),
        t("style", "style.synthwave", "Synthwave"),
        t("style", "style.retrowave", "Retrowave"),
        t("style", "style.chillwave", "Chillwave"),
        t("style", "style.drone", "Drone"),
        t("style", "style.noise", "Noise"),
        t("style", "style.electro", "Electro"),
        t("style", "style.ebm", "EBM"),
        t("style", "style.industrial", "Industrial"),
        t("style", "style.electronica", "Electronica"),
        t("style", "style.old_school_hip_hop", "Old School Hip-Hop"),
        t("style", "style.boom_bap", "Boom Bap"),
        t("style", "style.trap", "Trap"),
        t("style", "style.drill", "Drill"),
        t("style", "style.cloud_rap", "Cloud Rap"),
        t("style", "style.conscious_hip_hop", "Conscious Hip-Hop"),
        t("style", "style.alternative_hip_hop", "Alternative Hip-Hop"),
        t("style", "style.experimental_hip_hop", "Experimental Hip-Hop"),
        t("style", "style.jazz_rap", "Jazz Rap"),
        t("style", "style.lofi_hip_hop", "Lo-fi Hip-Hop"),
        t("style", "style.gangsta_rap", "Gangsta Rap"),
        t("style", "style.east_coast_hip_hop", "East Coast Hip-Hop"),
        t("style", "style.west_coast_hip_hop", "West Coast Hip-Hop"),
        t("style", "style.southern_hip_hop", "Southern Hip-Hop"),
        t("style", "style.crunk", "Crunk"),
        t("style", "style.grime", "Grime"),
        t("style", "style.phonk", "Phonk"),
        t("style", "style.emo_rap", "Emo Rap"),
        t("style", "style.contemporary_rnb", "Contemporary R&B"),
        t("style", "style.alternative_rnb", "Alternative R&B"),
        t("style", "style.neo_soul", "Neo Soul"),
        t("style", "style.soul", "Soul"),
        t("style", "style.motown", "Motown"),
        t("style", "style.philly_soul", "Philly Soul"),
        t("style", "style.quiet_storm", "Quiet Storm"),
        t("style", "style.new_jack_swing", "New Jack Swing"),
        t("style", "style.funk", "Funk"),
        t("style", "style.p_funk", "P-Funk"),
        t("style", "style.funk_rock", "Funk Rock"),
        t("style", "style.gospel_soul", "Gospel Soul"),
        t("style", "style.traditional_jazz", "Traditional Jazz"),
        t("style", "style.dixieland", "Dixieland"),
        t("style", "style.swing", "Swing"),
        t("style", "style.big_band", "Big Band"),
        t("style", "style.bebop", "Bebop"),
        t("style", "style.hard_bop", "Hard Bop"),
        t("style", "style.cool_jazz", "Cool Jazz"),
        t("style", "style.modal_jazz", "Modal Jazz"),
        t("style", "style.free_jazz", "Free Jazz"),
        t("style", "style.jazz_fusion", "Jazz Fusion"),
        t("style", "style.smooth_jazz", "Smooth Jazz"),
        t("style", "style.latin_jazz", "Latin Jazz"),
        t("style", "style.afro_cuban_jazz", "Afro-Cuban Jazz"),
        t("style", "style.vocal_jazz", "Vocal Jazz"),
        t("style", "style.gypsy_jazz", "Gypsy Jazz"),
        t("style", "style.nu_jazz", "Nu Jazz"),
        t("style", "style.acid_jazz", "Acid Jazz"),
        t("style", "style.jazz_funk", "Jazz-Funk"),
        t("style", "style.baroque", "Baroque"),
        t("style", "style.classical_period", "Classical Period"),
        t("style", "style.romantic", "Romantic"),
        t("style", "style.modern_classical", "Modern Classical"),
        t("style", "style.contemporary_classical", "Contemporary Classical"),
        t("style", "style.minimalism", "Minimalism"),
        t("style", "style.impressionism", "Impressionism"),
        t("style", "style.chamber_music", "Chamber Music"),
        t("style", "style.orchestral", "Orchestral"),
        t("style", "style.symphony", "Symphony"),
        t("style", "style.concerto", "Concerto"),
        t("style", "style.sonata", "Sonata"),
        t("style", "style.opera", "Opera"),
        t("style", "style.choral", "Choral"),
        t("style", "style.sacred_classical", "Sacred Classical"),
        t("style", "style.solo_piano", "Solo Piano"),
        t("style", "style.string_quartet", "String Quartet"),
        t("style", "style.ballet", "Ballet"),
        t("style", "style.neoclassical", "Neoclassical"),
        t("style", "style.classical_crossover", "Classical Crossover"),
        t("style", "style.traditional_folk", "Traditional Folk"),
        t("style", "style.contemporary_folk", "Contemporary Folk"),
        t("style", "style.indie_folk", "Indie Folk"),
        t("style", "style.singer_songwriter", "Singer-Songwriter"),
        t("style", "style.americana", "Americana"),
        t("style", "style.bluegrass", "Bluegrass"),
        t("style", "style.celtic", "Celtic"),
        t("style", "style.nordic_folk", "Nordic Folk"),
        t("style", "style.balkan_folk", "Balkan Folk"),
        t("style", "style.neofolk", "Neofolk"),
        t("style", "style.traditional_country", "Traditional Country"),
        t("style", "style.contemporary_country", "Contemporary Country"),
        t("style", "style.alt_country", "Alt-Country"),
        t("style", "style.outlaw_country", "Outlaw Country"),
        t("style", "style.honky_tonk", "Honky Tonk"),
        t("style", "style.country_pop", "Country Pop"),
        t("style", "style.delta_blues", "Delta Blues"),
        t("style", "style.chicago_blues", "Chicago Blues"),
        t("style", "style.electric_blues", "Electric Blues"),
        t("style", "style.acoustic_blues", "Acoustic Blues"),
        t("style", "style.country_blues", "Country Blues"),
        t("style", "style.soul_blues", "Soul Blues"),
        t("style", "style.roots_reggae", "Roots Reggae"),
        t("style", "style.dub", "Dub"),
        t("style", "style.ska", "Ska"),
        t("style", "style.rocksteady", "Rocksteady"),
        t("style", "style.dancehall", "Dancehall"),
        t("style", "style.ragga", "Ragga"),
        t("style", "style.two_tone", "2 Tone"),
        t("style", "style.bossa_nova", "Bossa Nova"),
        t("style", "style.samba", "Samba"),
        t("style", "style.salsa", "Salsa"),
        t("style", "style.tango", "Tango"),
        t("style", "style.bachata", "Bachata"),
        t("style", "style.merengue", "Merengue"),
        t("style", "style.reggaeton", "Reggaeton"),
        t("style", "style.latin_pop", "Latin Pop"),
        t("style", "style.latin_rock", "Latin Rock"),
        t("style", "style.cumbia", "Cumbia"),
        t("style", "style.mariachi", "Mariachi"),
        t("style", "style.afrobeat", "Afrobeat"),
        t("style", "style.afrobeats", "Afrobeats"),
        t("style", "style.highlife", "Highlife"),
        t("style", "style.soukous", "Soukous"),
        t("style", "style.middle_eastern", "Middle Eastern"),
        t("style", "style.arabic_pop", "Arabic Pop"),
        t("style", "style.indian_classical", "Indian Classical"),
        t("style", "style.hindustani", "Hindustani Classical"),
        t("style", "style.carnatic", "Carnatic"),
        t("style", "style.bollywood", "Bollywood"),
        t("style", "style.qawwali", "Qawwali"),
        t("style", "style.flamenco", "Flamenco"),
        t("style", "style.fado", "Fado"),
        t("style", "style.french_chanson", "French Chanson"),
        t("style", "style.japanese_traditional", "Japanese Traditional"),
        t("style", "style.korean_traditional", "Korean Traditional"),
        t("style", "style.chinese_traditional", "Chinese Traditional"),
        t("style", "style.guofeng", "国风"),
        t("style", "style.gufeng", "古风"),
        t("style", "style.minyue", "民乐"),
        t("style", "style.xiqu", "戏曲"),
        t("style", "style.mongolian", "蒙古音乐"),
        t("style", "style.tibetan", "藏族音乐"),
        t("style", "style.xinjiang", "新疆民族音乐"),
        t("style", "style.film_score", "Film Score"),
        t("style", "style.tv_score", "TV Score"),
        t("style", "style.game_soundtrack", "Game Soundtrack"),
        t("style", "style.anime_soundtrack", "Anime Soundtrack"),
        t("style", "style.musical_theatre", "Musical Theatre"),
        t("style", "style.cinematic", "Cinematic"),
        t("style", "style.trailer_music", "Trailer Music"),
        t("style", "style.library_music", "Library Music"),
        t("style", "style.new_age", "New Age"),
        t("style", "style.meditation_music", "Meditation Music"),
        t("style", "style.easy_listening", "Easy Listening"),
        t("style", "style.lounge", "Lounge"),
        t("style", "style.exotica", "Exotica"),
        t("style", "style.christmas", "Christmas"),
        t("style", "style.childrens_music", "Children's Music"),
        t("style", "style.comedy_music", "Comedy Music"),
        t("style", "style.spoken_word", "Spoken Word"),
        t("style", "style.experimental", "Experimental"),
        t("style", "style.avant_garde", "Avant-Garde"),
        t("style", "style.sound_art", "Sound Art"),
        t("vocal", "vocal.instrumental", "器乐 / 无人声"),
        t("vocal", "vocal.male_lead", "男主唱"),
        t("vocal", "vocal.female_lead", "女主唱"),
        t("vocal", "vocal.mixed_lead", "男女混合主唱"),
        t("vocal", "vocal.duet", "对唱"),
        t("vocal", "vocal.ensemble", "多人合唱"),
        t("vocal", "vocal.choir", "合唱团"),
        t("vocal", "vocal.children", "童声"),
        t("vocal", "vocal.group_vocal", "群体人声"),
        t("vocal", "vocal.harmony_prominent", "和声突出"),
        t("vocal", "vocal.rap", "说唱"),
        t("vocal", "vocal.half_sung_half_rap", "半说半唱"),
        t("vocal", "vocal.spoken_word", "念白"),
        t("vocal", "vocal.recitation", "朗诵"),
        t("vocal", "vocal.chant", "吟唱"),
        t("vocal", "vocal.a_cappella", "清唱"),
        t("vocal", "vocal.whisper", "低语"),
        t("vocal", "vocal.breathy", "气声"),
        t("vocal", "vocal.falsetto", "假声"),
        t("vocal", "vocal.powerful_lead", "高亢唱法"),
        t("vocal", "vocal.strong_vocal", "强力唱法"),
        t("vocal", "vocal.operatic", "歌剧唱法"),
        t("vocal", "vocal.bel_canto", "美声"),
        t("vocal", "vocal.soul_vocal", "灵魂唱腔"),
        t("vocal", "vocal.melisma", "转音突出"),
        t("vocal", "vocal.shout", "呼喊"),
        t("vocal", "vocal.scream", "尖叫"),
        t("vocal", "vocal.growl", "嘶吼"),
        t("vocal", "vocal.harsh_vocal", "Growl"),
        t("vocal", "vocal.clean_vocal", "Clean Vocal"),
        t("vocal", "vocal.vocoder", "Vocoder / 机器人声"),
        t("vocal", "vocal.sampled_vocal", "采样人声"),
        t("vocal", "vocal.humming", "哼唱"),
        t("vocal", "vocal.call_and_response", "Call and Response"),
        t("instrument", "instrument.piano", "钢琴"),
        t("instrument", "instrument.electric_piano", "电钢琴"),
        t("instrument", "instrument.synthesizer", "合成器"),
        t("instrument", "instrument.organ", "管风琴"),
        t("instrument", "instrument.acoustic_guitar", "木吉他"),
        t("instrument", "instrument.electric_guitar", "电吉他"),
        t("instrument", "instrument.distorted_guitar", "失真吉他"),
        t("instrument", "instrument.bass", "贝斯"),
        t("instrument", "instrument.upright_bass", "低音提琴"),
        t("instrument", "instrument.drums", "架子鼓"),
        t("instrument", "instrument.drum_machine", "鼓机"),
        t("instrument", "instrument.percussion", "打击乐"),
        t("instrument", "instrument.eight_oh_eight", "808"),
        t("instrument", "instrument.violin", "小提琴"),
        t("instrument", "instrument.cello", "大提琴"),
        t("instrument", "instrument.strings", "弦乐组"),
        t("instrument", "instrument.orchestra", "管弦乐团"),
        t("instrument", "instrument.trumpet", "小号"),
        t("instrument", "instrument.trombone", "长号"),
        t("instrument", "instrument.french_horn", "圆号"),
        t("instrument", "instrument.brass", "铜管组"),
        t("instrument", "instrument.saxophone", "萨克斯"),
        t("instrument", "instrument.flute", "长笛"),
        t("instrument", "instrument.clarinet", "单簧管"),
        t("instrument", "instrument.woodwinds", "木管组"),
        t("instrument", "instrument.harp", "竖琴"),
        t("instrument", "instrument.accordion", "手风琴"),
        t("instrument", "instrument.harmonica", "口琴"),
        t("instrument", "instrument.banjo", "班卓"),
        t("instrument", "instrument.mandolin", "曼陀林"),
        t("instrument", "instrument.ukulele", "尤克里里"),
        t("instrument", "instrument.sitar", "西塔琴"),
        t("instrument", "instrument.tabla", "塔布拉鼓"),
        t("instrument", "instrument.erhu", "二胡"),
        t("instrument", "instrument.guzheng", "古筝"),
        t("instrument", "instrument.pipa", "琵琶"),
        t("instrument", "instrument.dizi", "笛子"),
        t("instrument", "instrument.xiao", "箫"),
        t("instrument", "instrument.suona", "唢呐"),
        t("instrument", "instrument.guqin", "古琴"),
        t("instrument", "instrument.yangqin", "扬琴"),
        t("instrument", "instrument.chinese_percussion", "民族打击乐"),
        t("instrument", "instrument.sampler", "采样器"),
        t("instrument", "instrument.turntable", "Turntable / Scratch"),
        t("instrument", "instrument.field_recording", "环境采样"),
        t("instrument", "instrument.bells", "钟声 / Chime"),
        t("instrument", "instrument.marimba", "木琴 / 马林巴"),
        t("texture", "texture.acoustic", "原声质感"),
        t("texture", "texture.electronic", "电子质感"),
        t("texture", "texture.organic", "有机质感"),
        t("texture", "texture.synthetic", "合成质感"),
        t("texture", "texture.warm", "温暖"),
        t("texture", "texture.cold", "冷色"),
        t("texture", "texture.bright", "明亮"),
        t("texture", "texture.dark", "暗色"),
        t("texture", "texture.transparent", "通透"),
        t("texture", "texture.airy", "空气感"),
        t("texture", "texture.rich", "丰润"),
        t("texture", "texture.thick", "厚实"),
        t("texture", "texture.dense", "密集"),
        t("texture", "texture.sparse", "稀疏"),
        t("texture", "texture.minimal", "极简"),
        t("texture", "texture.intricate", "繁复"),
        t("texture", "texture.clean", "干净"),
        t("texture", "texture.refined", "精致"),
        t("texture", "texture.rough", "粗糙"),
        t("texture", "texture.gritty", "粗粝"),
        t("texture", "texture.distorted", "失真"),
        t("texture", "texture.grainy", "颗粒感"),
        t("texture", "texture.noisy", "噪音感"),
        t("texture", "texture.smooth", "平滑"),
        t("texture", "texture.silky", "丝滑"),
        t("texture", "texture.soft", "柔软"),
        t("texture", "texture.hard", "硬朗"),
        t("texture", "texture.sharp", "尖锐"),
        t("texture", "texture.dry", "干声"),
        t("texture", "texture.reverb_rich", "混响丰富"),
        t("texture", "texture.spacious", "空间宽阔"),
        t("texture", "texture.close", "近距离"),
        t("texture", "texture.immersive", "包围感"),
        t("texture", "texture.wide_stereo", "宽立体声"),
        t("texture", "texture.analog", "模拟味"),
        t("texture", "texture.digital", "数字感"),
        t("texture", "texture.retro_production", "复古制作"),
        t("texture", "texture.future_production", "未来制作"),
        t("texture", "texture.lofi", "Lo-fi"),
        t("texture", "texture.hifi", "Hi-fi"),
        t("texture", "texture.live", "现场感"),
        t("texture", "texture.studio", "录音室感"),
        t("texture", "texture.cinematic", "电影感"),
        t("texture", "texture.atmospheric", "氛围化"),
        t("texture", "texture.impactful", "冲击感"),
        t("texture", "texture.deep_bass", "厚重低频"),
        t("texture", "texture.clear_highs", "清澈高频"),
        t("texture", "texture.shimmering", "闪亮"),
        t("texture", "texture.hazy", "朦胧"),
        t("texture", "texture.glitch", "Glitch"),
        t("texture", "texture.dreamy_production", "Dreamy Production"),
        t("texture", "texture.wall_of_sound", "Wall of Sound"),
        t("rhythm", "rhythm.straight", "直拍"),
        t("rhythm", "rhythm.swing", "Swing"),
        t("rhythm", "rhythm.shuffle", "Shuffle"),
        t("rhythm", "rhythm.syncopated", "切分"),
        t("rhythm", "rhythm.four_on_floor", "Four-on-the-floor"),
        t("rhythm", "rhythm.breakbeat", "Breakbeat"),
        t("rhythm", "rhythm.half_time", "Half-time"),
        t("rhythm", "rhythm.double_time", "Double-time"),
        t("rhythm", "rhythm.driving", "强推进"),
        t("rhythm", "rhythm.loose_groove", "松弛律动"),
        t("rhythm", "rhythm.funk_groove", "Funk Groove"),
        t("rhythm", "rhythm.latin_groove", "Latin Groove"),
        t("rhythm", "rhythm.afro_groove", "Afro Groove"),
        t("rhythm", "rhythm.reggae_offbeat", "Reggae Offbeat"),
        t("rhythm", "rhythm.triple_meter", "三拍子"),
        t("rhythm", "rhythm.compound_meter", "复合拍"),
        t("rhythm", "rhythm.polyrhythm", "Polyrhythm"),
        t("rhythm", "rhythm.odd_meter", "Odd Meter"),
        t("rhythm", "rhythm.steady_pulse", "稳定脉冲"),
        t("rhythm", "rhythm.free_time", "自由节拍"),
        t("rhythm", "rhythm.rubato", "Rubato"),
        t("rhythm", "rhythm.march", "March"),
        t("rhythm", "rhythm.motorik", "Motorik"),
        t("rhythm", "rhythm.trap_hi_hat", "Trap Hi-hat"),
        t("rhythm", "rhythm.boom_bap_groove", "Boom Bap Groove"),
        )
    }

    val byId: Map<String, RecommendationTagDefinition> by lazy {
        definitions.associateBy { it.id }
    }

    val textualDimensions: Set<String> = setOf(
        "mood", "scene", "theme", "genre", "style", "vocal", "instrument", "texture", "rhythm",
    )

    fun definition(id: String): RecommendationTagDefinition? = byId[id]

    fun isKnownTextTag(dimension: String, id: String): Boolean =
        dimension in textualDimensions && byId[id]?.dimension == dimension

    /** Compact prompt catalog: stable ID plus Chinese display name, without aliases. */
    fun compactCatalog(): String = definitions.joinToString(separator = "\n") { definition ->
        "${definition.id}=${definition.displayName}"
    }
}
